
   
name: Create Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 */3 * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Install library and other requirements
      run: |
        pip install jupyter nbconvert
        pip install -r requirements.txt 
    - name: Run Notebooks
      env:
        GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      run: |
         jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --inplace --execute fumblevsint.ipynb
         jupyter nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --inplace --execute RunVPass.ipynb
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
          default_author: github_actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
