
   
name: Create Report
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 */3 * * *" 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install library and other requirements
      run: |
        pip install jupyter nbconvert
        pip install -r requirements.txt 
    - name: Run Notebooks
      env:
        GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      run: |
         jupyter nbconvert --to notebook --execute fumblevsint.ipynb
         jupyter nbconvert --to notebook --execute RunVPass.ipynb
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Jerry Gamblin
        message: "Update NFL Stats"
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
